import Head from "next/head";
import { Navbar } from "../components/Navbar";

export default function Play() {
	return (
		<div>
			<Head>
				<title>Taylor Che - Play</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<main className="xl:px-28 2xl:px-48 ">
				{/* text */}

				<div className="w-full h-50">
					<h1 className="bg-gradient-to-r from-blue-200 to-pink-300 bg-clip-text text-6xl text-transparent font-black select-none h-20 mt-20">
						Book/Show Recs!
					</h1>

					<div>
						<h1 className="text-2xl text-blue-400 mb-4">Books</h1>
						<BookEntry
							title={"About Face"}
							author={"David Hackworth, Julie Sherman"}
							completed={true}
						/>

						<BookEntry
							title={"You’re Not Listening"}
							author={"Kate Murphy"}
							completed={false}
						/>
						<BookEntry
							title={"Don’t Make Me Think"}
							author={"Steve Krug"}
							completed={true}
						/>
						<BookEntry
							title={"You Just Don’t Understand"}
							author={"Deborah Tannen"}
							completed={true}
						/>
					</div>
					<div className="mt-4">
						<h1 className="text-2xl text-blue-400 mb-4">Shows/Films</h1>

						{/* Abstract  •  Netflix DocumentaryMinimalist  •  Netflix Documentary

Invincible  •  Amazon PrimeUndone  •  Rotoscoped animated showAny Studio Ghibli film  •  I love Ghibli!! */}
						<FilmEntry
							title={"The Social Dilemma"}
							type={"Netflix Documentary"}
						/>
						<FilmEntry title={"Abstract"} type={"Netflix Documentary"} />
						<FilmEntry title={"Minimalist"} type={"Netflix Documentary"} />
						<FilmEntry title={"Invincible"} type={"Amazon Prime"} />
						<FilmEntry title={"Undone"} type={"Rotoscoped Animated Show"} />
						<FilmEntry
							title={"Any Studio Ghibli film"}
							type={"I love Ghibli!!!"}
						/>
					</div>
				</div>
			</main>

			<footer></footer>
		</div>
	);
}

const FilmEntry = ({ title, type }) => (
	<div className="flex item-center mt-4 text-lg">
		<p className="font-bold">{title} • </p>
		<p className="mx-1">{type}</p>
	</div>
);

const BookEntry = ({ title, author, completed }) => (
	<div className="flex item-center mt-4 text-lg">
		<p className="font-bold">{title} - </p>
		<p className="mx-1">{author}</p>
		<p className="mr-1">•</p>

		{completed ? (
			<p className="font-bold tracking-wide text-blue-400 ml-1">COMPLETED</p>
		) : (
			<p className="font-bold tracking-wide text-purple-400 ml-1">
				IN PROGRESS
			</p>
		)}
	</div>
);
